#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  case "$#" in
    0)
      local nm_repo="$(cat ".repo-name")"
      ;;
    *)
      local nm_repo="$1"; shift
      ;;
  esac

  local nm_repo="${nm_repo//\//--}"
  local url_repo="$(git cc "$nm_repo" 2>/dev/null || true)"
  if [[ -z "$url_repo" ]]; then
    aws codecommit create-repository --repository-name "$nm_repo"
    git cc aws "$nm_repo"
  fi
}

source sub "$BASH_SOURCE" "$@"
