#!/usr/bin/env bash

function version {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local ver_codecommit="0.0.1"
  jq -n --arg codecommit "$ver_codecommit" '{codecommit: $codecommit}'
}

version "$@"
